# Generated by Django 2.2.1 on 2019-05-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_executed', models.DateTimeField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('ready', 'Ready')], default='ready', max_length=10)),
                ('document', models.FileField(upload_to='job_documents/')),
                ('scheduling', models.IntegerField(choices=[('running', 'Running'), ('failed', 'Failed'), ('ready', 'Ready')], default='none')),
            ],
        ),
    ]
