# Generated by Django 2.2.1 on 2019-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_executed',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduling',
            field=models.IntegerField(choices=[(0, 'none'), (1, '1 hour'), (2, '2 hours'), (6, '6 hours'), (12, '12 hours')], default=0),
        ),
    ]
