# Generated by Django 2.2.1 on 2019-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190513_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='document',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
